### ISSUE TITLE
Exception throws on deleting objects declared using var

### ISSUE THREAD

**Issue by rajasegar** [single-spa/single-spa-leaked-globals#7]
if a global object is declared using `var`, then it can't be deleted with the `delete` operator. I think we need to handle this exception.

```
Uncaught TypeError: application 'people' died in status UNMOUNTING: Cannot delete property 'require' of #<Window>
    at single-spa-leaked-globals.js:51
```

**Comment by filoxo** [comment]
If I understand correctly, this is just the nature of JavaScript, globally declared variables, and host objects. See http://perfectionkills.com/understanding-delete/#summary I'll also copy the relevant lines here (emphasis added):

> Here's a short summary of how deletion works in Javascript:
>
> - Variables and function declarations are properties of either Activation or Global objects.
> - Properties have attributes, one of which — DontDelete — is responsible for whether a property can be deleted.
> - **Variable and function declarations in Global and Function code always create properties with DontDelete.**
> ...
> - Host objects are allowed to react to deletion however they want.

The ["`delete` and host objects"](http://perfectionkills.com/understanding-delete/#delete_and_host_objects) is also a good section to refer to. 

Because of that, I don't think there's anything that this helper should do to support this case.

**Comment by filoxo** [comment]
I'm going to go ahead and close this as there doesn't seem to be an issue or enhancement to add to single-spa-leaked-globals but feel free to ask any additional questions or reopen if needs be.
